# docker-compose.yml

version: '3.8'

services:
  db:
    image: nouchka/sqlite:latest
    container_name: sqlite_db
    volumes:
      - sqlite_data:/app/db
    networks:
      - app_network

  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  sqlite_data:

networks:
  app_network:
    driver: bridge
